// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/storage/storage.proto

package storage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Storage struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwnerId              string   `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Storage) Reset()         { *m = Storage{} }
func (m *Storage) String() string { return proto.CompactTextString(m) }
func (*Storage) ProtoMessage()    {}
func (*Storage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87989e2875259d4, []int{0}
}

func (m *Storage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Storage.Unmarshal(m, b)
}
func (m *Storage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Storage.Marshal(b, m, deterministic)
}
func (m *Storage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Storage.Merge(m, src)
}
func (m *Storage) XXX_Size() int {
	return xxx_messageInfo_Storage.Size(m)
}
func (m *Storage) XXX_DiscardUnknown() {
	xxx_messageInfo_Storage.DiscardUnknown(m)
}

var xxx_messageInfo_Storage proto.InternalMessageInfo

func (m *Storage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Storage) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Storage) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Storage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Storage) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Storage) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type Specification struct {
	Capacity             int32    `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87989e2875259d4, []int{1}
}

func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (m *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(m, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Specification) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

type Response struct {
	Storage              *Storage   `protobuf:"bytes,1,opt,name=storage,proto3" json:"storage,omitempty"`
	Storages             []*Storage `protobuf:"bytes,2,rep,name=storages,proto3" json:"storages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87989e2875259d4, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStorage() *Storage {
	if m != nil {
		return m.Storage
	}
	return nil
}

func (m *Response) GetStorages() []*Storage {
	if m != nil {
		return m.Storages
	}
	return nil
}

func init() {
	proto.RegisterType((*Storage)(nil), "storage.Storage")
	proto.RegisterType((*Specification)(nil), "storage.Specification")
	proto.RegisterType((*Response)(nil), "storage.Response")
}

func init() { proto.RegisterFile("proto/storage/storage.proto", fileDescriptor_c87989e2875259d4) }

var fileDescriptor_c87989e2875259d4 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0x4d, 0xff, 0x24, 0x99, 0x97, 0x16, 0x9d, 0x83, 0xac, 0x55, 0x21, 0xe4, 0x14,
	0x44, 0x2a, 0xd4, 0xab, 0x17, 0x2f, 0x82, 0x1e, 0x3c, 0x24, 0x07, 0x8f, 0x65, 0x9b, 0x1d, 0xeb,
	0x40, 0x93, 0x0d, 0x49, 0x68, 0xeb, 0xc7, 0xf1, 0x9b, 0x0a, 0x6b, 0x36, 0x55, 0x11, 0x4f, 0x3b,
	0xf3, 0xdb, 0x67, 0x96, 0x67, 0x9e, 0x85, 0xb3, 0xaa, 0x36, 0xad, 0xb9, 0x6e, 0x5a, 0x53, 0xab,
	0x35, 0xb9, 0x73, 0x6e, 0x29, 0xfa, 0x5d, 0x1b, 0xbf, 0x0b, 0xf0, 0xb3, 0xcf, 0x1a, 0xa7, 0xe0,
	0xb1, 0x96, 0x22, 0x12, 0xc9, 0x28, 0xf5, 0x58, 0xe3, 0x0c, 0x82, 0x5c, 0x55, 0x2a, 0xe7, 0xf6,
	0x4d, 0x7a, 0x96, 0xf6, 0x3d, 0x5e, 0x00, 0x14, 0x6a, 0xbf, 0xdc, 0x11, 0xaf, 0x5f, 0x5b, 0x39,
	0xb0, 0xb7, 0x61, 0xa1, 0xf6, 0xcf, 0x16, 0x20, 0xc2, 0xb0, 0x54, 0x05, 0xc9, 0x61, 0x24, 0x92,
	0x30, 0xb5, 0x35, 0x9e, 0x43, 0xa8, 0xb6, 0x8a, 0x37, 0x6a, 0xb5, 0x21, 0x39, 0x8a, 0x44, 0x12,
	0xa4, 0x07, 0x80, 0xa7, 0x10, 0x98, 0x5d, 0x49, 0xf5, 0x92, 0xb5, 0x1c, 0xdb, 0x29, 0xdf, 0xf6,
	0x0f, 0x3a, 0x7e, 0x84, 0x49, 0x56, 0x51, 0xce, 0x2f, 0x9c, 0xab, 0x96, 0x4d, 0xf9, 0xcd, 0x98,
	0xf8, 0xd3, 0x98, 0xf7, 0xc3, 0x58, 0xac, 0x21, 0x48, 0xa9, 0xa9, 0x4c, 0xd9, 0x10, 0x5e, 0x82,
	0x8b, 0xc1, 0xbe, 0xf2, 0x7f, 0x71, 0x34, 0x77, 0x29, 0x75, 0x91, 0xa4, 0x4e, 0x80, 0x57, 0x10,
	0x74, 0x65, 0x23, 0xbd, 0x68, 0xf0, 0xab, 0xb8, 0x57, 0x2c, 0x9e, 0x60, 0xda, 0xc1, 0x8c, 0xea,
	0x2d, 0xe7, 0x84, 0xb7, 0x30, 0xb9, 0xe7, 0x52, 0xdf, 0xf5, 0xfb, 0x9e, 0x1c, 0xc6, 0xbf, 0xee,
	0x36, 0x3b, 0xee, 0xb9, 0xf3, 0x19, 0xff, 0x5b, 0x8d, 0xed, 0xaf, 0xdd, 0x7c, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xfe, 0x73, 0x2b, 0x27, 0xd4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for StorageService service

type StorageServiceClient interface {
	FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error)
}

type storageServiceClient struct {
	c           client.Client
	serviceName string
}

func NewStorageServiceClient(serviceName string, c client.Client) StorageServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "storage"
	}
	return &storageServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *storageServiceClient) FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "StorageService.FindAvailable", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StorageService service

type StorageServiceHandler interface {
	FindAvailable(context.Context, *Specification, *Response) error
}

func RegisterStorageServiceHandler(s server.Server, hdlr StorageServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&StorageService{hdlr}, opts...))
}

type StorageService struct {
	StorageServiceHandler
}

func (h *StorageService) FindAvailable(ctx context.Context, in *Specification, out *Response) error {
	return h.StorageServiceHandler.FindAvailable(ctx, in, out)
}
